// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_hotel_1.EF;

#nullable disable

namespace web_hotel_1.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20220426144817_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("web_hotel_1.EF.HotelContext+Class_EF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClassList_EF");
                });

            modelBuilder.Entity("web_hotel_1.EF.HotelContext+Room_EF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassIDId")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_places")
                        .HasColumnType("int");

                    b.Property<string>("Room_empty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassIDId");

                    b.ToTable("Rooms_EF");
                });

            modelBuilder.Entity("web_hotel_1.EF.HotelContext+Room_EF", b =>
                {
                    b.HasOne("web_hotel_1.EF.HotelContext+Class_EF", "ClassID")
                        .WithMany()
                        .HasForeignKey("ClassIDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassID");
                });
#pragma warning restore 612, 618
        }
    }
}
